// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzA3l6ZKWqn1ooctlA-lcwLuy2KeuoBOc',
    appId: '1:860748541996:web:4e342d1857badb0a9fe189',
    messagingSenderId: '860748541996',
    projectId: 'flutter-project-78239',
    authDomain: 'flutter-project-78239.firebaseapp.com',
    databaseURL: 'https://flutter-project-78239-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-78239.firebasestorage.app',
    measurementId: 'G-6ETK53LY3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdJbE3bu8BdOzXqZPsZ3shYV0vLIO3cuQ',
    appId: '1:860748541996:android:9fc93fff37e2de209fe189',
    messagingSenderId: '860748541996',
    projectId: 'flutter-project-78239',
    databaseURL: 'https://flutter-project-78239-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-78239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLmQ4_fXoznePSIo-w3HCsxwyh-U4DHiU',
    appId: '1:860748541996:ios:3884cbd173b42df29fe189',
    messagingSenderId: '860748541996',
    projectId: 'flutter-project-78239',
    databaseURL: 'https://flutter-project-78239-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-78239.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLmQ4_fXoznePSIo-w3HCsxwyh-U4DHiU',
    appId: '1:860748541996:ios:3884cbd173b42df29fe189',
    messagingSenderId: '860748541996',
    projectId: 'flutter-project-78239',
    databaseURL: 'https://flutter-project-78239-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-78239.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzA3l6ZKWqn1ooctlA-lcwLuy2KeuoBOc',
    appId: '1:860748541996:web:7421a76dd90592689fe189',
    messagingSenderId: '860748541996',
    projectId: 'flutter-project-78239',
    authDomain: 'flutter-project-78239.firebaseapp.com',
    databaseURL: 'https://flutter-project-78239-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-project-78239.firebasestorage.app',
    measurementId: 'G-CS08S8LFY1',
  );

}